name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  pre_deploy_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:5000
  deployment_job:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-20.04
    needs: pre_deploy_tests
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
  bump_version:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-20.04
    needs: [pre_deploy_tests, deployment_job]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.40.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
